### ISSUE TITLE
User-specific files shouldn't be tracked

### ISSUE THREAD

**Issue by elijahsullivan** [solidlikeplato/tic-tac-toe-java#3]
The `.idea/workspace.xml` file should not be tracked in version control since it is user-specific.

I noticed the `.idea` directory was added to the `.gitignore` in #1, but that happened after the file was tracked and included as a commit. Since it was never removed in a commit after it was added to the `.gitignore` it still appears on master.

The following command will remove the file from the working tree so you can create a commit with this file excluded:

`git rm --cached .idea/workspace.xml`

There are some files worth tracking in `.idea` so I would reconsider ignoring the entire directory. More on this here: https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore

**Comment by ericmeyer** [comment]
A huge +1 to adding parts of that directory to version control. My rule of thumb is that while I (typically) do not want to enforce use of a particular IDE, it is fine to make it easy and convenient to use a given IDE.

That, and it is also a great way to make sure everyone has the same build configuration so the application does not behave differently for different developers.

**Comment by whaley-ethan** [comment]
removed
